title: Non-Standard Deviations
description: A collection of uncertainty musings on research methods and statistics.
theme: just-the-docs

url: https://michaelides.github.io/non-sd

#aux_links:
#  Template Repository: 
