title: Non-Standard Deviations
description: A collection of research methods, and statistical recipies!
theme: just-the-docs

url: https://michaelides.github.io/non-sd

#aux_links:
#  Template Repository: 
